### ISSUE TITLE
请问一下怎么生成脚本文件

### ISSUE THREAD

**Issue by LynahZ** [woshica/JiaGuoMeng-AutoClicker#2]
powershell报错如下

> PS D:\Aria2_Downloads> python .\JiaGuoMeng.py -epicId 5 -lvup 0 --yellow-only                                           Traceback (most recent call last):
  File ".\JiaGuoMeng.py", line 203, in <module>
    autoTrainYellowOnly()
  File ".\JiaGuoMeng.py", line 184, in autoTrainYellowOnly
    j = newMission.generateJson("自动火车发货(仅黄色)", "Y")
  File ".\JiaGuoMeng.py", line 113, in generateJson
    a = open("output\\" + name + ".json", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'output\\自动火车发货(仅黄色).json'

**Comment by LynahZ** [comment]
手动创建对应文件就行了
再次感谢！
