### ISSUE TITLE
windows环境下运行报错

### ISSUE THREAD

**Issue by osgg** [woshica/JiaGuoMeng-AutoClicker#5]
python版本3.7.4，运行的时候报错：
c:\jia>python JiaGuoMeng.py -lvup 3
Traceback (most recent call last):
  File "JiaGuoMeng.py", line 207, in <module>
    autoUpgrade()
  File "JiaGuoMeng.py", line 140, in autoUpgrade
    j = newMission.generateJson("自动升级建筑", "U")
  File "JiaGuoMeng.py", line 113, in generateJson
    a = open("output\\" + name + ".json", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'output\\自动升级建筑.json'

c:\jia>python JiaGuoMeng.py -epicId 3 -lvup 1 --train
Traceback (most recent call last):
  File "JiaGuoMeng.py", line 205, in <module>
    autoTrain()
  File "JiaGuoMeng.py", line 160, in autoTrain
    j = newMission.generateJson("自动火车发货", "T")
  File "JiaGuoMeng.py", line 113, in generateJson
    a = open("output\\" + name + ".json", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'output\\自动火车发货.json'

c:\jia>
c:\jia>python JiaGuoMeng.py --train
Traceback (most recent call last):
  File "JiaGuoMeng.py", line 205, in <module>
    autoTrain()
  File "JiaGuoMeng.py", line 160, in autoTrain
    j = newMission.generateJson("自动火车发货", "T")
  File "JiaGuoMeng.py", line 113, in generateJson
    a = open("output\\" + name + ".json", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'output\\自动火车发货.json'

c:\jia>python JiaGuoMeng.py --train
Traceback (most recent call last):
  File "JiaGuoMeng.py", line 205, in <module>
    autoTrain()
  File "JiaGuoMeng.py", line 160, in autoTrain
    j = newMission.generateJson("自动火车发货", "T")
  File "JiaGuoMeng.py", line 113, in generateJson
    a = open("output\\" + name + ".json", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'output\\自动火车发货.json'

**Comment by woshica** [comment]
在根目录创建一个叫output的文件夹即可。我稍后会在代码中修复这个问题。
